### ISSUE TITLE
Relax Node engine requirement to 16

### ISSUE THREAD

**Issue by khanetor** [insectos/node-red-cloudflare-ddns#1]
**Is your feature request related to a problem? Please describe.**
Most Node-Red docker images run Node 16 or 18, so it seems unreasonable to require the *node engine > 20.0.0*.

**Describe the solution you'd like**
Relax the requirement to allow engine from Node 16 and later.

**Additional context**
This is useful because most people run Node Red in a containerized environment with Docker images.

**Comment by Stwissel** [comment]
Nope. I don't have bandwidth to test. Node20 is LTS and the latest NodeRED container runs on 20

**Comment by khanetor** [comment]
> Nope. I don't have bandwidth to test. Node20 is LTS and the latest NodeRED container runs on 20

That is quite not the case. The highest Node version by the NodeRED community is still 18, and 16 is the default. We have many different version for LTS.

Check the latest information here https://hub.docker.com/r/nodered/node-red/tags
